
name: 'Stale issue handler'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-issue-message: 'This issue has been automatically marked as stale after 30d because it has not had
          recent activity. It will be closed in 5d if no further activity occurs. Thank you for your contributions.'
          days-before-stale: 30
          days-before-close: 5
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security,block'